### ISSUE TITLE
Enable students to view the grades

### ISSUE THREAD

**Issue by umumtaz1** [umumtaz1/practice-github-flow#1]
**User story**:

As a student, I want to have access to my grade online so that I can stay up to date and improve academic performance.

*persona: student
*feature: have access to grades online
*business value: Student can stay up to date and improve academic performance.

**Tasks List**

- [x] Make sure the database is storing the grades correctly. 
- [ ] Use HTML and CSS to make the website user friendly. 
- [ ] Associate the HTML with the database.

**Acceptance Criteria**
1. Only for classes of the current semester
2. Works only for Chrome.

**Acceptance Tests**
1. Student should be able to view current grades online.
2. Student should be able to see the exact percentage of the total grade.
